// central store for all query keys
export enum queryKeys {
  ALL_VENDORS = "ALL_VENDORS",
  ALL_TRANSACTIONS = "ALL_TRANSACTIONS",
  FUND_TRANSACTIONS = "FUND_TRANSACTIONS",
  VENDOR = "VENDOR",
  TRANSACTION = "TRANSACTION",
  VENDOR_WALLET_RECORDS = "VENDOR_WALLET_RECORDS",
  CURRENT_VENDOR_DETAILS = "CURRENT_VENDOR_DETAILS",
}
